//
//  op_management.h
//  jvm
//
//

#ifndef jvm_op_management_h
#define jvm_op_management_h

//Opcodes
#define OP_aaload           0x32h
#define OP_aastore          0x53h
#define OP_aconst_null      0x01h
#define OP_aload            0x19h
#define OP_aload_0          0x2ah
#define OP_aload_1          0x2bh
#define OP_aload_2          0x2ch
#define OP_aload_3          0x2dh
#define OP_anewarray        0xbdh
#define OP_areturn          0xb0h
#define OP_arraylength      0xbeh
#define OP_astore           0x3ah
#define OP_astore_0         0x4bh
#define OP_astore_1	        0x4ch
#define OP_astore_2         0x4dh
#define OP_astore_3         0x4eh
#define OP_athrow           0xbfh
#define OP_baload           0x33h
#define OP_bastore          0x54h
#define OP_bipush           0x10h
#define OP_breakpoint	    0xcah
#define OP_caload           0x34h
#define OP_castore          0x55h
#define OP_checkcast        0xc0h
#define OP_d2f              0x90h
#define OP_d2i              0x8eh
#define OP_d2l              0x8fh
#define OP_dadd             0x63h
#define OP_daload           0x31h
#define OP_dastore          0x52h
#define OP_dcmpg            0x98h
#define OP_dcmpl            0x97h
#define OP_dconst_0         0x0eh
#define OP_dconst_1         0x0fh
#define OP_ddiv             0x6fh
#define OP_dload            0x18h
#define OP_dload_0          0x26h
#define OP_dload_1          0x27h
#define OP_dload_2          0x28h
#define OP_dload_3          0x29h
#define OP_dmul             0x6bh
#define OP_dneg             0x77h
#define OP_drem             0x73h
#define OP_dreturn          0xafh
#define OP_dstore           0x39h
#define OP_dstore_0         0x47h
#define OP_dstore_1         0x48h
#define OP_dstore_2         0x49h
#define OP_dstore_3         0x4ah
#define OP_dsub             0x67h
#define OP_dup              0x59h
#define OP_dup_x1           0x5ah
#define OP_dup_x2           0x5bh
#define OP_dup2             0x5ch
#define OP_dup2_x1          0x5dh
#define OP_dup2_x2          0x5eh
#define OP_f2d              0x8dh
#define OP_f2i              0x8bh
#define OP_f2l              0x8ch
#define OP_fadd             0x62h
#define OP_faload           0x30h
#define OP_fastore          0x51h
#define OP_fcmpg            0x96h
#define OP_fcmpl            0x95h
#define OP_fconst_0         0x0bh
#define OP_fconst_1         0x0ch
#define OP_fconst_2         0x0dh
#define OP_fdiv             0x6eh
#define OP_fload            0x17h
#define OP_fload_0          0x22h
#define OP_fload_1          0x23h
#define OP_fload_2          0x24h
#define OP_fload_3          0x25h
#define OP_fmul             0x6ah
#define OP_fneg             0x76h
#define OP_frem             0x72h
#define OP_freturn          0xaeh
#define OP_fstore           0x38h
#define OP_fstore_0         0x43h
#define OP_fstore_1         0x44h
#define OP_fstore_2         0x45h
#define OP_fstore_3         0x46h
#define OP_fsub             0x66h
#define OP_getfield         0xb4h
#define OP_getstatic        0xb2h
#define OP_goto             0xa7h
#define OP_goto_w           0xc8h
#define OP_i2b              0x91h
#define OP_i2c              0x92h
#define OP_i2d              0x87h
#define OP_i2f              0x86h
#define OP_i2l              0x85h
#define OP_i2s              0x93h
#define OP_iadd             0x60h
#define OP_iaload           0x2eh
#define OP_iand             0x7eh
#define OP_iastore          0x4fh
#define OP_iconst_m1        0x02h
#define OP_iconst_0         0x03h
#define OP_iconst_1         0x04h
#define OP_iconst_2         0x05h
#define OP_iconst_3         0x06h
#define OP_iconst_4         0x07h
#define OP_iconst_5         0x08h
#define OP_idiv             0x6ch
#define OP_if_acmpeq        0xa5h
#define OP_if_acmpne        0xa6h
#define OP_if_icmpeq        0x9fh
#define OP_if_icmpge        0xa2h
#define OP_if_icmpgt        0xa3h
#define OP_if_icmple        0xa4h
#define OP_if_icmplt        0xa1h
#define OP_if_icmpne        0xa0h
#define OP_ifeq             0x99h
#define OP_ifge             0x9ch
#define OP_ifgt             0x9dh
#define OP_ifle             0x9eh
#define OP_iflt             0x9bh
#define OP_ifne             0x9ah
#define OP_ifnonnull        0xc7h
#define OP_ifnull           0xc6h
#define OP_iinc             0x84h
#define OP_iload            0x15h
#define OP_iload_0          0x1ah
#define OP_iload_1          0x1bh
#define OP_iload_2          0x1ch
#define OP_iload_3          0x1dh
#define OP_impdep1          0xfeh
#define OP_impdep2          0xffh
#define OP_imul             0x68h
#define OP_ineg             0x74h
#define OP_instanceof       0xc1h
#define OP_invokedynamic	0xbah
#define OP_invokeinterface	0xb9h
#define OP_invokespecial	0xb7h
#define OP_invokestatic     0xb8h
#define OP_invokevirtual	0xb6h
#define OP_ior              0x80h
#define OP_irem             0x70h
#define OP_ireturn          0xach
#define OP_ishl             0x78h
#define OP_ishr             0x7ah
#define OP_istore           0x36h
#define OP_istore_0         0x3bh
#define OP_istore_1         0x3ch
#define OP_istore_2         0x3dh
#define OP_istore_3         0x3eh
#define OP_isub             0x64h
#define OP_iushr            0x7ch
#define OP_ixor             0x82h
#define OP_jsr              0xa8h
#define OP_jsr_w            0xc9h
#define OP_l2d              0x8ah
#define OP_l2f              0x89h
#define OP_l2i              0x88h
#define OP_ladd             0x61h
#define OP_laload           0x2fh
#define OP_land             0x7fh
#define OP_lastore          0x50h
#define OP_lcmp             0x94h
#define OP_lconst_0         0x09h
#define OP_lconst_1         0x0ah
#define OP_ldc              0x12h
#define OP_ldc_w            0x13h
#define OP_ldc2_w           0x14h
#define OP_ldiv             0x6dh
#define OP_lload            0x16h
#define OP_lload_0          0x1eh
#define OP_lload_1          0x1fh
#define OP_lload_2          0x20h
#define OP_lload_3          0x21h
#define OP_lmul             0x69h
#define OP_lneg             0x75h
#define OP_lookupswitch     0xabh
#define OP_lor              0x81h
#define OP_lrem             0x71h
#define OP_lreturn          0xadh
#define OP_lshl             0x79h
#define OP_lshr             0x7bh
#define OP_lstore           0x37h
#define OP_lstore_0         0x3fh
#define OP_lstore_1         0x40h
#define OP_lstore_2         0x41h
#define OP_lstore_3         0x42h
#define OP_lsub             0x65h
#define OP_lushr            0x7dh
#define OP_lxor             0x83h
#define OP_monitorenter     0xc2h
#define OP_monitorexit      0xc3h
#define OP_multianewarray	0xc5h
#define OP_new              0xbbh
#define OP_newarray         0xbch
#define OP_nop              0x00h
#define OP_pop              0x57h
#define OP_pop2             0x58h
#define OP_putfield         0xb5h
#define OP_putstatic        0xb3h
#define OP_ret              0xa9h
#define OP_return           0xb1h
#define OP_saload           0x35h
#define OP_sastore          0x56h
#define OP_sipush           0x11h
#define OP_swap             0x5fh
#define OP_tableswitch      0xaah
#define OP_wide             0xc4h


#endif
